project:
  type: website
  output-dir: docs

website:
  title: "An educator's perspective of the tidyverse"
  description: "Code and supplementary materials for the An educator's perspective of the tidyverse talk."
  site-url: "https://mine-cetinkaya-rundel.github.io/tidyperspective/"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2022, Mine Çetinkaya-Rundel"

  sidebar:
    style: "docked"
    tools:
      - icon: github
        href: https://github.com/mine-cetinkaya-rundel/tidyperspective
    contents:
      - href: index.qmd
        text: Home
      - href: paper.qmd
        text: Paper

format:
  html:
    theme: cosmo
    css: styles.css
    mainfont: "Atkinson Hyperlegible"

editor: visual

execute:
  freeze: auto